<div class="footer">
    <div class="footerTop">
        <div class="footerSocial">
            <h2>Suivez-Nous</h2>
            <div class="social">
                <a href="https://fr-fr.facebook.com/"><img src="public/medias/logo-facebook.png" alt="logo facebook"></a>
                <a href="https://twitter.com/home?lang=fr"><img src="public/medias/logo-twitter.png" alt="logo twitter"></a>
                <a href="https://www.instagram.com"><img src="public/medias/logo-instagram.png" alt="logo instagram"></a>
                <a href="https://www.tiktok.com/fr/"><img src="public/medias/logo-tiktok.png" alt="logo tiktok"></a>
                <!--<a href="" id="btnModalContact"><img src="public/medias/logo-mail.png" alt=""></a>-->
                <a href="mailto:cinemall@domaine.fr?subject=Objet%20du%20message&body=Corps%20du%20message"><img src="public/medias/logo-mail.png" alt="logo enveloppe"></a>
            </div>
        </div>
        <div class="footerAppli">
            <h2>CinemALL sur mobile</h2>
            <div>
                <a href="https://www.youtube.com/watch?v=sCNrK-n68CM"><img src="public/medias/logo-apple.png" alt=""></a>
                <a href="https://www.youtube.com/watch?v=G1IbRujko-A&t=23s"><img src="public/medias/logo-android.png" alt=""></a>
            </div>
        </div>
        <div class="footerCountry">
            <h2>CinemALL à l'étranger</h2>
            <div class="country">
                <a href="">Allemagne</a>
                <a href="">Espagne</a>
                <a href="">Turquie</a>
                <a href="">Brésil</a>
                <a href="">Mexique</a>
            </div>
        </div>
    </div>
    <div class="footerBottom">
        <div class="footerB1">
            <a href="mailto:cinemall@domaine.fr?subject=Objet%20du%20message&body=Corps%20du%20message">Contact  |</a>
            <a href="index.php?page=about&action=execute">Qui sommes-nous  |</a>
            <a href="https://webedia-group.com/">Recrutement  |</a>
            <a href="http://specs.webedia.fr/">Publicité  |</a>
            <a href="index.php?page=cgu&action=execute">CGU  |</a>
            <a href="index.php?page=cookies&action=execute">Politique de cookies  |</a>
            <a href="index.php?page=data&action=execute">Données Personnelles  |</a>
            <span> ©CinemALL</span>
        </div>
        <p>Retrouvez tous les horaires et infos de votre cinéma sur le numéro <span>CinemALL</span> : 0 195 402 352 (0,90€/minute) </p>
        <div class="footerB2">
            <img src="public/medias/logo1.png" alt="logo-cinemall">
        </div>
        <span class="copyRight">Copyright ©<?= date('Y') ?> @<?= SITE ?></span>
    </div>
</div>