<?php
	ini_set('display_errors', 'on');
	require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta name="description" content="CGU CinemALL">
	<?php require "includes/partials/page_head.phtml"; ?>
	<link href='https://fonts.googleapis.com/css?family=Russo+One' rel='stylesheet'>
	<link rel="stylesheet" href="public/styles/styles.css" type="text/css">
</head>
<body>
	<nav>
		<?php require_once "includes/partials/navbar.phtml"; ?>
	</nav>
	<header>
		<h1 class="cguH1">Ensemble des règlements régissant la participation des internautes au site CinemALL</h1>
	</header>
	<main class="content">
		<p class="cgu">
            Conditions Générales d’Utilisation

            (Dernière mise à jour le 17/06/2021)
            
            Les présentes conditions générales d’utilisation (ci-après « les Conditions Générales ») sont conclues entre la société CinemALL, 2, 
            rue Paul Vaillant Couturier 92300 Levallois-Perret (ci-après « CinemALL ») et l’Utilisateur, tel qu’identifié lors du processus d’ouverture 
            du compte utilisateur (ci-après « l’Utilisateur »).
            1. Edition et hébergement du site Internet CinemALL.fr
            1.1. Edition du Site Internet CinemALL.fr
            
            Le site Allocine.fr est édité par la société WEBEDIA.
            
                Siren: 501 106 520 RCS Paris
                Siège social : 2, rue Paul Vaillant Couturier 92300 Levallois-Perret (France)
                Capital social : 1 301 656,18 €
                Directeur de la Publication : Cédric Sire
                Responsable de la rédaction : Monsieur Yoann Sardet
                Contact : +33 184200984
            
            1.2. Hébergement du Site
            
            Le Site est hébergé par Webedia
            
            Adresse : 2, rue Paul Vaillant Couturier - CS 60102 - 92532 Levallois-Perret Cedex
        </p> 
        <p class="cgu">
            2. Objet des Conditions Générales

            AlloCiné propose à l’Utilisateur, sur son site Internet accessible à l’adresse https://www.allocine.fr, (ci-après « le Site »), différents services 
            liés notamment au cinéma et séries télévisées (ci-après les « Services »). Les Services sont présentés sur les pages du Site. Par Service(s), on entend, 
            sans que cette liste soit limitative, les contenus proposés, les éléments de mise en valeur des contenus, la mise à disposition d’outils, notamment 
            l’outil de lecture de contenus vidéos (ci-après désigné par le terme « Lecteur(s) ») et plus généralement tout autre service proposé par AlloCiné 
            et disponible notamment à l’adresse : https://www.allocine.fr et/ou à toute autre adresse qui viendrait s’ajouter ou de substituer à celle-ci.
            
            AlloCiné se réserve le droit d'ajouter, de supprimer ou de modifier tout ou partie des espaces des Services qu’elle propose.
            
            AlloCiné se réserve le droit de mettre à jour, de modifier et/ou de supprimer tout ou partie des Services à tout moment et sans préavis.
            
            Les présentes Conditions Générales ont pour objet de régir la mise à disposition et/ou l’accès par l’Utilisateur à ces Services et l’utilisation 
            qu’il en fait.
            
            L’accès et l’utilisation de tout ou partie des Services proposés sur le Site impliquent de la part de l’Utilisateur une acceptation pleine 
            et entière de l’ensemble des présentes Conditions Générales.
            
            L’Utilisateur confirme donc avoir lu et compris l’intégralité des présentes Conditions Générales avant toute utilisation des Services. 
            L’Utilisateur s’engage à respecter les présentes Conditions Générales.
            
            L’acceptation des Conditions Générales exclut l’application de toute disposition différente ou contraire. Les stipulations des présentes 
            Conditions Générales prévaudront en toute hypothèse.
            
            Toute utilisation des Services contraire aux Conditions Générales est prohibée et sanctionnée, conformément à l’article 9 des présentes 
            Conditions Générales.
            
            Les Conditions Générales constituent l’intégralité du contrat passé entre l’Utilisateur et AlloCiné et, le cas échéant, annulent et remplacent 
            l’ensemble des contrats, négociations et ententes antérieures entre l’Utilisateur et AlloCiné.
            
            AlloCiné pourra proposer des conditions particulières complémentaires relatives à certains Services spécifiques, qui doivent être acceptées 
            par l’Utilisateur s’il souhaite avoir accès aux dits Services.
        </p> 
        <p class="cgu">
            3. Accès aux Services

            Seules les personnes ayant ouvert un compte utilisateur (ci-après dénommé le « Compte » ou « Compte Utilisateur ») et, pour ce faire, 
            dûment rempli le formulaire comportant toutes les informations obligatoires (matérialisées par un astérisque) demandées par AlloCiné et 
            ayant consenti sans réserve aux présentes Conditions Générales d’Utilisation peuvent avoir accès et utiliser les Services soumis à un accès. 
            Ces services sont notamment les suivants :
            
                possibilité de noter et de rédiger des appréciations sur les films, séries et personnalités
                publication de critiques
                choix de cinémas favoris
                publication de commentaires
                choix d’amis
                configuration du profil
                accès et participation aux forums AlloCiné
                participation aux jeux-concours AlloCiné
                réception d’alertes et de newsletters par email
            
            Cette inscription peut s’effectuer soit par le Site, soit, le cas échéant, selon d’autres modalités proposées par AlloCiné, 
            et notamment par l’utilisation d’outils nomades (dont les téléphones portables).
            
            Les autres Services proposés par AlloCiné sont en accès libre.
            
            AlloCiné peut créer des nouveaux services soumis à un accès et/ou décider qu’un service en accès libre sera soumis à un accès.
        </p> 
        <p class="cgu">
            4. Ouverture d’un Compte Utilisateur (inscription de l’Utilisateur)

            L’Utilisateur est amené à communiquer à AlloCiné des informations personnelles, qui permettront ensuite de l’identifier et de faciliter 
            l’accès sécurisé au Site et aux Services et l’utilisation des Services.
            
            L’Utilisateur doit ainsi communiquer : ses nom, prénom, date de naissance, adresse électronique.
            
            Lorsque l’Utilisateur remplit le formulaire d’inscription aux Services, il s’engage à le remplir correctement, et notamment à ne 
            communiquer que des informations exactes, à jour et complètes.
            
            L’Utilisateur s’engage à mettre à jour les informations le concernant à chaque changement de sa situation. L’Utilisateur s’engage à 
            effectuer ces modifications sur le Site directement depuis son Compte.
            
            Si AlloCiné a connaissance que tout ou partie des informations communiquées lors de l’inscription sont erronées ou incomplètes, AlloCiné 
            se réserve le droit de suspendre et/ou clôturer le Compte de l’Utilisateur et/ou de bloquer tout nouvel accès et/ou usage des Services, 
            sans préjudice de tout autre recours ou action.
            
            L’inscription entraîne l’acceptation expresse et sans réserve par l’Utilisateur des présentes Conditions Générales matérialisée par le 
            « cochage » obligatoire de la case d’acceptation des Conditions Générales « J’ai lu et j’accepte l’ensemble des règles édictées par les présentes 
            Conditions Générales d’Utilisation ». L’Utilisateur s’engage à conserver sur un support durable les Conditions Générales d’Utilisation qui lui 
            sont fournies par AlloCiné sur un tel support.
            
            En cliquant sur le bouton « J’ai lu et j’accepte l’ensemble des règles édictées par les présentes Conditions Générales d’Utilisation », 
            l'Utilisateur reconnaît qu'il a la capacité juridique pour conclure une telle convention ou qu'il dispose de l'autorisation de la personne habilitée.
            
            L’Utilisateur a la possibilité de s’inscrire en utilisant son compte Facebook. En cas d’inscription via le compte Facebook de l’Utilisateur, 
            ce dernier est seul responsable du respect de ses obligations vis-à-vis de Facebook. En cas de contradiction entre les conditions générales 
            de Facebook et les présentes Conditions Générales, les stipulations des Conditions Générales prévaudront en toute hypothèse.
        </p> 
        <p class="cgu">
            5. Identifiants et mot de passe

            Lors de son inscription, l’Utilisateur est amené à rentrer son adresse email servant à l’identifier (l’ « Identifiant de Connexion ») et à permettre 
            une connexion plus rapide lors de l’utilisation des Services ainsi qu’à choisir un mot de passe d'au moins quatre caractères alphanumériques 
            (le « Mot de Passe »).
            
            Lors de son inscription, l’Utilisateur doit également choisir un pseudonyme (ci-après le « Pseudo »). Le Pseudo est différent de l’identifiant de 
            connexion. Le Pseudo est visible des autres Utilisateurs. Le Pseudo identifie l’Utilisateur en tant que personne.
            
            L’Utilisateur s’engage à choisir un Identifiant de Connexion et un Pseudo qui soient disponibles et licites. Il s’interdit notamment de choisir 
            un Identifiant de Connexion ou un Pseudo pouvant porter atteinte à un quelconque droit de propriété intellectuelle, nom commercial ou droit 
            de la personnalité de tiers.
            
            L’Identifiant de Connexion et le Pseudo choisis par l’Utilisateur ne doivent en outre pas :
            
                faire référence à une orientation politique, à une ethnie, une communauté, une religion,
                être vulgaires ou insultants,
                avoir de connotation sexuelle voire pornographique,
                faire référence à un produit stupéfiant ou toute autre substance interdite par la législation française,
                faire référence à des boissons alcoolisées, au tabac ou aux produits du tabac,
                être orthographié ou épelé alternativement dans le but de contourner les règles imposées ci-dessus.
            
            AlloCiné se réserve le droit de supprimer et/ou de demander à récupérer des Identifiants de Connexion, à tout moment et quelle qu’en soit 
            la raison, et notamment, sans toutefois s’y limiter, en raison de prétentions de tiers indiquant qu’un identifiant constitue une violation de leurs droits.
            
            L’Utilisateur accepte que sur le Site son nom ou Pseudo soient accessibles publiquement, et les conséquences attachées, notamment le fait 
            que certains moteurs de recherche puissent les indexer, sans que la responsabilité de AlloCiné puisse être engagée.
            
            Le Mot de Passe est personnel et confidentiel. L’Utilisateur en est seul responsable. Il s’engage à ne pas le divulguer à des tiers et 
            à prendre toutes les précautions nécessaires pour éviter que des tiers puissent y avoir accès.
            
            Pour garantir la sécurité de son Compte, l’Utilisateur s’engage à :
            
                ne pas divulguer à des tiers ni son Identifiant de Connexion, ni son Mot de Passe ;
                prendre toutes les précautions nécessaires pour éviter que des tiers puissent y avoir accès ;
                prendre toutes les mesures afin d’éviter qu’un tiers puisse accéder au Compte que l’Utilisateur a activé, même à son insu ;
                ne pas donner accès à son Compte à un tiers ;
                utiliser une boîte courriel personnelle et ne pas partager cette adresse ;
                ce qu’AlloCiné puisse facilement entrer en contact avec l’Utilisateur, pour quelque raison que ce soit, via son adresse courriel.
            
            Le prêt, le partage, l’échange, le don, l’achat, le transfert et la vente de Comptes sont interdits. Tout prêt, partage, échange, achat, 
            transfert ou vente de Compte ne sera pas opposable à AlloCiné et pourra donner lieu aux sanctions prévues à l’article 9 des présentes Conditions Générales.
            
            L’Utilisateur est seul responsable de l’utilisation de son Compte. Toute connexion ou transmission d’ordres ou de données effectuée 
            au moyen de son Mot de Passe sera réputée avoir été effectuée par lui-même et sous sa responsabilité exclusive.
            
            Afin de préserver le caractère personnel et confidentiel de son accès, il est recommandé à l’Utilisateur de se déconnecter de son Compte 
            à la fin de chaque session d’accès en cliquant sur « Me déconnecter » ou toute mention similaire proposée.
            
            En cas d’utilisation frauduleuse de son Compte et/ou Mot de Passe, ou en cas de perte ou de vol de son Mot de Passe, l’Utilisateur s’engage 
            à en informer immédiatement AlloCiné.
            
            Dans le cas où l’Utilisateur suspecte raisonnablement une faille dans la sécurité, y compris la perte, le vol ou l’utilisation non autorisée 
            de son identifiant de connexion et mot de passe ou tout autre problème lié à la sécurité de son Compte, il doit avertir immédiatement AlloCiné. 
            AlloCiné pourra alors réinitialiser son mot de passe.
            
            AlloCiné pourra également bloquer l’accès au Compte en question.
            
            En cas d’oubli du Mot de Passe, l’Utilisateur le signale sur la page d’ouverture du Site en cliquant sur la rubrique «J’ai oublié mon mot 
            de passe ». Dans ce cas, l’Utilisateur doit renseigner son Identifiant de Connexion et recevra à l’adresse électronique renseignée lors 
            de son inscription un courriel lui indiquant un nouveau mot de passe.
        </p>
        <p class="cgu">
            6. Protection des données à caractère personnel
            
            6.1. Conformément à la loi n°78-17 du 6 janvier 1978 modifiée, relative à l’informatique, aux fichiers et aux libertés, AlloCiné informe 
            l’Utilisateur qu’elle respecte la confidentialité, l’intégrité et la sécurité des données qu’il peut être amené à lui communiquer par le 
            biais du Site ou des Services.
            
            Toute donnée à caractère personnel identifiant indirectement ou directement l’Utilisateur, notamment : nom, prénom, coordonnées postales, 
            électroniques, téléphoniques, ou indirectement, est considérée selon la législation applicable comme une donnée confidentielle et traitée comme telle.
            
            Il est toutefois entendu que si l’Utilisateur choisit comme pseudonyme ses nom et prénom, il ne pourra opposer le caractère confidentiel 
            de ces données à AlloCiné.
            
            L’ouverture d’un Compte Utilisateur est soumise à la réalisation d’un traitement de données à caractère personnel dont le responsable est 
            CinemALL, ce que l’Utilisateur accepte.
            
            Ce traitement des données personnelles de l’Utilisateur est déclaré à la Commission Nationale de l'Informatique et des Libertés (CNIL).
            
            AlloCiné procède aux mises à jour de la déclaration CNIL si nécessaire.
            
            Les données collectées proviennent de la fourniture de leurs informations par les personnes désireuses d’accéder ou d’utiliser les Services 
            et de devenir Utilisateur.
            
            Les données pourront être utilisées pour les besoins de la gestion des opérations effectuées sur le Site et notamment l’accès et l’utilisation des Services.
            
            AlloCiné conserve les données personnelles de l’Utilisateur pour la durée nécessaire aux finalités décrites au présent article et aux fins 
            de conserver les éléments nécessaires en cas de mise en jeu de sa responsabilité contractuelle et/ou délictuelle. Au-delà de cette durée, 
            seules des données statistiques rendues anonymes seront conservées et ne donneront lieu à aucune exploitation, de quelque nature que ce soit.
            
            Sous réserve de justifier de son identité, l’Utilisateur dispose d'un droit d'accès, de modification, de rectification et de suppression 
            des données qui le concernent. L’Utilisateur peut mettre en œuvre ce droit en écrivant à AlloCiné à l'adresse électronique suivante 
            : dpo-ac@webedia-group.com, ou à l’adresse postale suivante: ALLOCINÉ, 2, rue Paul Vaillant Couturier 92300 Levallois-Perret.
            
            Conformément à l'article 32 loi informatique et libertés et au vu de cette Newsletter qui collecte des données personnelles, l'utilisateur 
            doit être informé de :
            
                De l'identité du responsable du traitement et, le cas échéant, de celle de son représentant
                De la finalité poursuivie par le traitement auquel les données sont destinées
                Du caractère obligatoire ou facultatif des réponses
                Des conséquences éventuelles, à son égard, d'un défaut de réponse
                Des destinataires ou catégories de destinataires des données
                Des droits qu'elle tient des dispositions de la section 2 du présent chapitre dont celui de définir des directives relatives au sort 
                de ses données à caractère personnel après sa mort
                Le cas échéant, des transferts de données à caractère personnel envisagés à destination d'un Etat non membre de la Communauté européenne
                De la durée de conservation des catégories de données traitées ou, en cas d'impossibilité, des critères utilisés permettant de déterminer cette durée.
            
            6.2. Pour des besoins statistiques, AlloCiné peut être amenée à recueillir des informations de navigation via l'utilisation de cookies. 
            L'acceptation de ces cookies est obligatoire pour toute souscription, gratuite ou payante.
            
            L’Utilisateur peut à tout moment supprimer l’enregistrement des cookies, ou les cookies déjà enregistrés sur son ordinateur, en paramétrant 
            les options de protection de la vie privée de son navigateur Internet (par exemple : Outils > Effacer mes traces > Cookies, sur Mozilla 
            Firefox et Outils > Supprimer l’historique de navigation > Supprimer les cookies, sur Microsoft Internet Explorer).
            
            AlloCiné se réserve également le droit de collecter certaines informations :
            
                liées à l’ordinateur de l’Utilisateur (IP, fournisseur d'accès, configuration matérielle, configuration logicielle)
                liées aux Services (log et historique de tous les échanges de données, « log » et historique des connexions).
            
            AlloCiné pourra utiliser ces informations à toutes fins, notamment pour cibler les bandeaux publicitaires, améliorer l'utilisation des 
            Services ou contrôler le respect des termes des présentes Conditions Générales.
            
            AlloCiné pourra par ailleurs transmettre les données de l’Utilisateur à des partenaires commerciaux, sous réserve de l’autorisation 
            expresse de l’Utilisateur lors de son inscription.
            
            Toutes les informations contenues sur les serveurs pourront être utilisées par AlloCiné pour effectuer tout type de contrôle à des fins 
            de prévention et de sanction.
            
            6.3. En règle générale, AlloCiné s’engage à ne pas divulguer les données personnelles de ses Utilisateurs, sauf avec leur autorisation 
            expresse ou dans des circonstances très particulières, telles celles qui sont envisagées et précisées dans les présentes Conditions 
            Générales, et notamment ;
            
                AlloCiné pourra être amenée – du fait de la loi, dans le cadre d’une procédure en justice, d’un litige et /ou d’une requête des 
                autorités publiques du pays de résidence de l’Utilisateur ou autre – à divulguer les données personnelles précitées ;
                AlloCiné pourra également divulguer ces données si la divulgation est nécessaire à des fins de sécurité nationale, d’application 
                de la loi ou autre sujet d’intérêt public ;
                AlloCiné peut également divulguer des données concernant ses Utilisateurs si cette divulgation est raisonnablement nécessaire pour 
                faire valoir le respect des présentes Conditions Générales ou protéger ses activités ou ses Utilisateurs ;
                en cas de restructuration ou de cession, AlloCiné pourra transférer toute donnée personnelle qu’elle conserve au tiers concerné.
        </p>
        <p class="cgu">
            7. Fourniture et Utilisation des Services
            7.1. Engagements et Responsabilité d’AlloCiné
            
            Aucun terme des présentes Conditions Générales n’affectera les droits d’ordre public auquel l’Utilisateur peut prétendre en qualité 
            de consommateur et auxquels l’Utilisateur ne peut renoncer en application d’un contrat.
            
            AlloCiné fournit les Services en l’état, et n’accorde aucune garantie à cet égard. En particulier, AlloCiné ne prend pas d’engagement 
            de disponibilité d’accès.
            
            Compte tenu notamment des aléas techniques liés au fonctionnement décentralisé du réseau Internet, AlloCiné ne fournit aucune garantie 
            de continuité de service ou d’absence d’erreurs des Services.
            
            Dans toute la mesure permise par la réglementation en vigueur, AlloCiné ne prend aucun engagement, express ou implicite, notamment 
            concernant la qualité et la compatibilité des Services aux usages de l’Utilisateur. Aucune information ou conseil donné par AlloCiné, 
            via les Services ou non, ne crée d’obligation pour AlloCiné ni de garantie.
            
            En particulier, Allociné ne déclare ni ne garantit :
            
                que l’utilisation des Services répondra aux besoins de l’Utilisateur ;
                que l’utilisation faite des Services par l’Utilisateur sera ininterrompue, opportune, sécurisée ou exempte d’erreurs ;
                que toute information obtenue en utilisant les Services sera exacte ou fiable ;
                que les défauts dans le fonctionnement ou les fonctionnalités de tout logiciel qui aura été fourni à l’Utilisateur dans le cadre 
                des Services seront corrigés.
            
            AlloCiné ne garantit pas que l’accès à tout ou partie des Services demeure gratuit pendant une durée indéfinie. En cas d’instauration 
            de nouveaux services payants ou de modification d’un service gratuit en un service payant, des Conditions Spécifiques d’Utilisation 
            seront proposés à l’Utilisateur au préalable, ou le cas échéant de nouvelles Conditions Générales d’Utilisation.
            
            Sous réserve des garanties expressément prévues aux présentes Conditions Générales, aucune condition, garantie ou autre terme (y compris 
            toute garantie implicite de qualité satisfaisante, d’adéquation à un usage particulier ou de conformité à la description) ne s’applique aux Services.
            
            Dans le cas où la responsabilité d’AlloCiné serait néanmoins engagée, la réparation ne s’appliquera qu’aux seuls dommages directs, personnels, 
            certains, à l’exclusion, sans que cette liste ne soit limitative, de tous dommages et/ou préjudices indirects et/ou immatériels, tels 
            que les préjudices commerciaux, moraux et financiers, y compris toute perte de bénéfices ayant pour cause, origine ou fondement 
            l’utilisation du Site ou des Services.
            
            En toute hypothèse, AlloCiné ne pourra voir sa responsabilité engagée en cas de faute ou de fait totalement ou partiellement imputable 
            à l’Utilisateur, à un tiers ou en cas de survenance d’un cas de force majeure.
            
            Dans tous les cas où la responsabilité d’AlloCiné pourrait être engagée, toute action ou réclamation quelle qu’elle soit ne pourrait 
            être engagée contre AlloCiné plus d'1 (un) an après le jour du manquement commis par AlloCiné.
            7.2. Responsabilité des partenaires
            
            Les Services présentés par les partenaires d’AlloCiné, le sont sous la seule responsabilité de ceux-ci. En conséquence, AlloCiné est 
            dégagée de toute responsabilité du fait des contenus édités et/ou des services proposés par les partenaires par l’intermédiaire du Site 
            et/ou des Services, ce que l’Utilisateur accepte expressément.
            7.3. Liens hypertextes
            
            Le Site peut contenir des liens hypertextes vers des contenus émanant de tiers ou vers des sites Internet exploités par des tiers.
            
            AlloCiné n’est pas responsable de la qualité ou de l'exactitude de ces contenus ni de ces sites Internet et ne peut pas non plus être 
            considérée comme approuvant, publiant ou autorisant ces sites Internet ou ces contenus.
            
            Par conséquent, les exploitants de ces sites sont seuls responsables du respect des législations et réglementations applicables, 
            notamment quant aux produits et services qu'ils mettent en vente sur leur site, et plus particulièrement en matière de protection 
            du consommateur, de vente à distance, réglementation des prix, protection des données personnelles, etc.
            
            AlloCiné décline toute responsabilité quant aux dommages pouvant résulter de l’utilisation de ces sites.
            7.4. Lecteurs
            
            Les contenus vidéos accessibles par le Site et les Services peuvent être visualisés à l’aide de lecteurs.
            
            L’utilisation des Lecteurs est réservée à un usage personnel et non commercial de l’Utilisateur, et uniquement à des fins de streaming sur le Site.
            
            AlloCiné se réserve seule le droit d’insérer ou d’autoriser tout tiers de son choix à insérer dans toutes pages du Site et/ou des Services 
            des messages publicitaires, promotionnels et/ou de parrainage, et notamment dans les Lecteurs.
            
            AlloCiné peut insérer ou autoriser tout tiers de son choix à insérer dans les Lecteurs avant ou après la visualisation des vidéos des 
            messages publicitaires, promotionnels ou de parrainage. Ces messages ne sont pas considérés comme étant incorporés dans les vidéos.
            
            Les Lecteurs peuvent offrir à l’Utilisateur des fonctionnalités lui permettant de choisir de rendre accessible des contenus à partir des 
            Lecteurs en dehors du Site. Cette simple fourniture de ces fonctionnalités n’implique aucune autorisation d’exploitation des contenus, 
            ces exploitations étant effectuées sous la seule responsabilité de l’Utilisateur, lequel devra faire son affaire de toute autorisation 
            éventuellement nécessaire pour une utilisation en dehors du Site.
            
            En aucun cas les Lecteurs ne peuvent être utilisés en dehors du Site à des fins commerciales ou publicitaires, ou associés à d’autres 
            contenus à des fins commerciales ou publicitaires.
            
            Il est également interdit à quiconque d’occulter, supprimer ou modifier tout message publicitaire diffusé avec les Lecteurs par AlloCiné.
            7.5. Propriété intellectuelle – Parasitisme – interdiction d’utilisation des données – Protection du Site et des bases de données
            
            Attention : Toutes les données et informations présentes ou accessibles par le site AlloCiné ne peuvent en aucun cas être reprises et 
            utilisées à d’autres fins que la consultation privée par l’Utilisateur directement connecté sur le Site. AlloCiné est et sera particulièrement 
            vigilante, et engagera toute action appropriée contre toute reprise quelconque effectuée en violation des droits de propriété intellectuelle 
            et/ou de la loi et /ou des Conditions Générales du site.
            
            Si l’Utilisateur souhaite utiliser dans un autre cadre, et/ou diffuser des données, informations et/ou des services du Site, il devra contacter AlloCiné :
            
            Téléphone : + 33 811 69 41 42
            Formulaire de contact : https://www.allocine.fr/service/contact/
            
            Les noms, images, logos ou tout autre signe distinctif présenté sur le Site identifiant AlloCiné et/ou ses partenaires et/ou des tiers 
            et/ou leurs produits et services sont des contenus protégés au titre des droits de propriété intellectuelle, et notamment du droit des 
            marques, du droit des dessins et modèles et/ou du droit d’auteur et des droits voisins, en France et à l’étranger.
            
            Les Services et leurs contenus, la structure générale du Site, des Services, les contenus éditoriaux, images, photographies, sons, 
            vidéos ou multimédias, les Lecteurs, les logiciels et les bases de données utilisés et tous les autres contenus présentés sur le Site 
            et dans les Services sont protégés au titre du droit d’auteur, des droits voisins et/ou du droit sui generis du producteur de base de 
            données, et d’une manière générale, par le droit commun de la responsabilité civile ainsi que par les conventions internationales applicables.
            
            AlloCiné et/ou ses partenaires sont seuls titulaires des droits de propriété intellectuelle susmentionnés sur l’ensemble des contenus 
            présentés sur le Site et dans les Services.
            
            L’Utilisateur s’engage à respecter ces droits.
            
            A ce titre, et sous peine de poursuites civiles et/ou pénales, sauf accord exprès d’AlloCiné, l’Utilisateur s’engage notamment à ne pas :
            
                reproduire, représenter, modifier, publier, adapter sur quelque support que ce soit, par quelque moyen que ce soit, l’ensemble des 
                éléments présents sur le Site et les Services ;
                procéder à une quelconque atteinte aux systèmes informatisés mis en œuvre pour la fourniture des Services, en ce compris toute intrusion 
                ou tentative d’intrusion ;
                procéder à une quelconque opération d’ingénierie inversée de tout ou partie des Services ;
                compiler, décompiler ou désassembler tout ou partie des Services ;
                modifier ou créer des programmes développés sur tout ou partie des Services, y compris pour corriger les éventuelles erreurs, 
                seule AlloCiné étant habilitée à effectuer les corrections éventuelles ;
                distribuer et/ou diffuser des copies de tout ou partie des Services ;
                enlever ou supprimer toute mention et/ou toute information propriétaire présente sur tout ou partie des Services ;
                revendre, louer, sous-louer ou transférer de quelque manière que ce soit à un tiers les Services.
            
            Toute utilisation des informations, données et des éléments du Site et des Services, à quelque titre que ce soit en dehors de la simple 
            consultation directe sur le Site par l’utilisateur, est strictement interdite, sauf autorisation préalable et par écrit d’AlloCiné.
            
            En aucun cas l’accès possible aux informations du Site et à certaines données ne peut permettre à l’utilisateur de considérer qu’il 
            peut extraire, de manière substantielle ou non, et/ou utiliser en dehors de la consultation du Site, une quelconque donnée du Site ou 
            de tout élément du Site. Il est rappelé que de telles extractions et/ou utilisations sont strictement interdites.
            
            Toute reproduction et/ou représentation, totale ou partielle, sur un quelconque support, des signes distinctifs ou contenus présentés 
            sur le Site, y compris les informations et/ou données, sans l’autorisation écrite préalable d’AlloCiné, de ses partenaires ou de tiers, 
            est interdite et constitutive notamment de contrefaçon et susceptible à ce titre d’engager la responsabilité civile et pénale de son auteur.
            
            Les fichiers numériques sur le Site peuvent être protégés par des mesures techniques de protection ou « systèmes de Digital Rights Management », 
            c’est-à-dire des systèmes de protection permettant de contrôler leur utilisation et en particulier leur copie. Ils ont notamment pour objectif 
            d’offrir à l’Utilisateur un maximum de flexibilité dans l’utilisation des contenus mis à disposition tout en protégeant les droits de 
            propriété intellectuelle.
            
            L’Utilisateur s’interdit de prendre toute mesure visant à contourner ou à porter atteinte aux techniques de contrôle des contenus numériques. 
            L’Utilisateur s’interdit en outre de porter atteinte de quelque façon que ce soit aux droits de reproduction, représentation et autres.
            
            Ces mesures techniques de protection et systèmes de Digital Rights Management sont régis par le code de la propriété intellectuelle. 
            Toute tentative de contournement de ces mesures est passible des sanctions prévues par ce même code. Plus généralement, toute utilisation 
            hors du cadre défini dans les présentes Conditions Générales serait assimilable à un acte de contrefaçon, qui expose l’Utilisateur 
            à des poursuites judiciaires, civiles ou pénales dans le cadre des dispositifs législatifs et réglementaires en vigueur.
            
            Compte tenu notamment de la protection juridique des mesures techniques et systèmes de Digital Rights Management en application des 
            dispositions du code de la propriété intellectuelle, l’Utilisateur ne peut transférer à un tiers ni la licence, ni les contenus, 
            ni les fichiers numériques.
            
            AlloCiné accorde aux gestionnaires de moteurs de recherche publics l’autorisation d’utiliser des spiders pour copier des données à 
            partir du site dans le seul but de créer des index de ces données consultables par le public, mais non des caches ou des archives 
            de ces données. AlloCiné se réserve le droit de révoquer ces exceptions soit de manière générale, soit dans des cas spécifiques.
            7.6 CIM Internet
            
            Ce site participe à l’Etude CIM Internet. Les sites qui reprennent le logo rassemblent des données sur le nombre de visiteurs et de 
            pages visitées à l’aide de cookies. Un cookie est un petit fichier texte qui est placé par un serveur sur le disque dur de votre ordinateur. 
            Aucun logiciel supplémentaire n’est installé. Un cookie n’endommage en rien votre matériel ou les programmes que vous utilisez.
            
            Les données qui sont récoltées dans le cadre de cette étude sont tout à fait anonymes. Elles servent uniquement à la comparaison 
            du nombre de visiteurs sur les sites participants. Vous trouverez de plus amples informations sur l’étude et sur les résultats de la 
            mesure sur le site du CIM.
        </p>
        <p class="cgu">
            
            8. Obligations et responsabilité des Utilisateurs
            8.1. Utilisation du Site et des Services
            
            L’Utilisateur s’engage, dans le cadre d’une obligation de résultat, à respecter les termes des présentes Conditions Générales.
            
            L’Utilisateur est tenu de respecter les règles de conduite indiquées ci-après.
            
            L’Utilisateur est ainsi tenu de ne pas utiliser les Services pour notamment :
            
                transmettre tout contenu à caractère pédophile ou portant atteinte d’une quelconque manière aux mineurs ou à la protection des 
                enfants et des adolescents ;
                envoyer, transmettre tout message dont le contenu est illégal, nuisible, menaçant, abusif, constitutif de harcèlement, diffamatoire, 
                vulgaire, obscène, menaçant pour la vie privée d'autrui, haineux, raciste, homophobe, antisémite, xénophobe, révisionniste ou autrement répréhensible ;
                transmettre tout contenu contraire à l’ordre public et aux bonnes mœurs ;
                transmettre tout contenu qui pourrait être constitutif, sans que ce qui suit soit limitatif, d’apologie ou d'incitation à la réalisation 
                de crimes et/ou délits, d’incitation au suicide, d’incitation à l’usage de drogues ou de substances interdites, de publicité indirecte
                pour des boissons alcoolisées, le tabac ou les produits du tabac ; d’incitation à commettre des attentats ; de provocation à la 
                discrimination, à la haine ou à la violence en raison de la race, de l'ethnie, de la religion ou de la nation, de fausses nouvelles ; 
                de fausses rumeurs ; d'atteinte à l'autorité de la justice, aux procès, à la divulgation d’informations relatives à une situation 
                fiscale individuelle ; de diffusion hors des conditions autorisées de sondages et simulations de vote relatifs à une élection ou un 
                référendum ; de diffamations et injures ; d'atteinte à la vie privée ; ou encore d'actes mettant en péril des mineurs notamment par 
                la fabrication, le transport, et la diffusion de messages à caractère violent ou pornographique ou de nature à porter gravement atteinte 
                à la personne humaine et à sa dignité, à l’égalité entre les femmes et les hommes ;
                transmettre tout contenu faisant état ou incitant à la cruauté envers les animaux ;
                transmettre tout message dont l’Utilisateur ne serait pas autorisé à diffuser le contenu notamment par une mesure législative ou 
                un acte juridique (notamment des informations internes, privilégiées, confidentielles, apprises ou divulguées dans le cadre d'un contrat
                de travail ou d'un accord de confidentialité sans que cette énumération soit limitative) ;
                transmettre tout message dont le contenu violerait tout brevet, marque déposée, dessin et modèle déposé, secret de fabrication, droit 
                d’auteur, droit voisin, droit de propriété intellectuelle ou tout autre droit de propriété appartenant à autrui, droit de la personnalité, 
                ou dont la publication serait susceptible de constituer une faute délictuelle ou quasi-délictuelle ;
                contrefaire des en-têtes, officiels ou non, ou manipuler de toute autre manière l'identifiant de manière à dissimuler l'origine du 
                contenu transmis via l’application ;
                collecter ou stocker des données en vue de créer une base de données concernant tout ou partie des Services ou les Utilisateurs des Services ;
                accéder ou tenter d’accéder au Compte d’un autre utilisateur des Services ;
                transmettre tout message contenant des virus informatiques ou tout autre code, dossier ou programme conçus pour interrompre, détruire ou 
                limiter la fonctionnalité de tout logiciel, ordinateur, système informatique ou outil de télécommunication sans que cette énumération soit limitative ;
                transmettre des messages incitant ou permettant tout acte de piratage informatique ou de contournement de dispositif technique de protection 
                (« crack ») ou d’information/mention sur les droits de propriété intellectuelle ;
                utiliser ou lancer un système automatisé (notamment robot, spider ou lecteur hors ligne) avec un accès aux Services de telle sorte qu’il 
                envoie plus de messages de requêtes aux serveurs AlloCiné pendant une période donnée que ne peut raisonnablement en produire un être humain 
                pendant la même période en utilisant un navigateur Internet standard (c’est-à-dire non modifié) disponible sur le marché ;
                entraver ou perturber les Services, les serveurs, les réseaux connectés au Site, ou refuser de se conformer aux conditions requises, 
                aux procédures, aux règles générales ou aux dispositions réglementaires applicables aux réseaux connectés au Site ;
                violer, intentionnellement ou non, toute loi ou réglementation locale, nationale ou internationale en vigueur ainsi que les limitations 
                contenues dans les présentes Conditions Générales ;
                usurper une identité ou se faire passer pour une autre personne ou entité, y compris pour un représentant officiel d’AlloCiné un animateur 
                et/ou administrateur des Services ;
                harceler de quelque manière que ce soit un autre ou plusieurs autres Utilisateurs des Services;
                donner des informations renvoyant vers d'autres sites (que ce soit par la création de liens hypertextes, ou par la seule fourniture 
                d'informations) dont le contenu serait susceptible de contrevenir à toute loi et réglementation en vigueur, et notamment serait 
                susceptible de porter atteinte aux droits des personnes et des biens, et/ou aux droits de propriété intellectuelle ;
                porter atteinte de quelque manière que ce soit à AlloCiné ses dirigeants et/ou collaborateurs et/ou ses Partenaires ou à leur image 
                et réputation, notamment en les insultant ou en les menaçant;
                utiliser les Services à des fins promotionnelles et commerciales et notamment, sans toutefois s’y limiter, pour diffuser ou faciliter 
                la diffusion de messages publicitaires ou de sollicitations ;
                utiliser tout ou partie des Services pour offrir d’autres services,
                collecter, stocker et diffuser des données personnelles afférentes aux autres Utilisateurs ou à tout tiers ;
                perturber ou tenter de perturber le bon fonctionnement des Services ;
                se connecter aux Services d’une manière non expressément prévue par les présentes Conditions Générales.
            
            L’Utilisateur s’engage à ne pas utiliser des failles, bugs informatiques ou toute autre forme d'erreur pour obtenir des avantages dans 
            l’utilisation des Services. De même, l’Utilisateur s’engage à avertir immédiatement AlloCiné lorsqu’il constate une faille ou une erreur dans les Services.
            
            L’Utilisateur s’engage à garantir et à indemniser AlloCiné, ses représentants, salariés, partenaires, et/ou tout tiers, contre tout dommage, 
            plainte ou demande émanant de tiers à la suite de l’utilisation des Services. Cette garantie couvre les indemnités qui seraient éventuellement 
            dues ainsi que les honoraires d’avocats dans une limite raisonnable et les frais de justice.
            
            L’Utilisateur s’engage à régler l’ensemble des frais et taxes applicables qui lui incombe au titre des opérations réalisées via son Compte Utilisateur.
            8.2. Fourniture de contenus par les Utilisateurs
            
            Les Services pourront prévoir des fonctionnalités telles que des forums de discussion dans lesquels l’Utilisateur pourra le cas échéant 
            publier du « contenu utilisateur ».
            
            Le « contenu utilisateur », généré par les Utilisateurs, fait référence à l’ensemble des critiques et commentaires que l’Utilisateur publie 
            sur le Site, ainsi qu’aux communications textes, images, vidéos, sons, matériels, données, observations, commentaires informations que 
            l’Utilisateur publie sur les forums du Site, télécharge ou transmet par le biais des Services, ou que d’autres Utilisateurs téléchargent 
            et/ou transmettent (ci-après dénommé « le Contenu utilisateur »).
            
            En sus des obligations stipulées à l’article 6.1, l’Utilisateur qui fournit un Contenu utilisateur est soumis aux obligations du présent article 6.2.
            
            AlloCiné ne peut garantir qu’elle-même ou d’autres Utilisateurs ne vont pas reprendre à leur compte les idées et informations qu’un Utilisateur 
            aurait choisi de partager via les Services.
            
            C’est pourquoi, si un Utilisateur tient à garder une idée ou une information secrète et/ou qu’il ne souhaite pas la voir utilisée par d’autres, 
            il lui incombe de ne pas la mettre en ligne par le biais des Services. Si l’Utilisateur soumet à AlloCiné des suggestions, des propositions, 
            des commentaires ou d’autres éléments (ci-après dénommés ensemble les « Soumissions ») dans le cadre des Services, AlloCiné n’aura aucune 
            obligation de maintenir ces Soumissions confidentielles, n’aura aucune obligation d’y répondre d’une quelconque manière, et pourra utiliser 
            ces Soumissions à toutes fins utiles, sans compensation ni rémunération, sans préjudice de l’application des autres stipulations pertinentes 
            des présentes.
            
            L’Utilisateur déclare être titulaire de tous les droits afférents au Contenu Utilisateur qu’il publie.
            
            L’Utilisateur s’engage à ce que le Contenu Utilisateur (sans que cette liste soit limitative) :
            
                ne constitue pas une violation de dispositions légales applicables, stipulations contractuelles ou autres droits de tiers, notamment 
                des droits de la personnalité ou des droits de propriété intellectuelle. En d’autres termes, l’Utilisateur ne mettra pas en ligne un 
                contenu, notamment vidéo, dont il n’est pas l’auteur et n’inclura pas dans sa vidéo du contenu pour lequel l’Utilisateur ne dispose 
                pas des droits s’il n’a pas obtenu les autorisations requises. Ces éléments peuvent être des pistes audio, des extraits de programme 
                protégés par des droits d’auteur ou des vidéos créées par un tiers ;
                ne comporte ni virus, ni logiciel publicitaire, ni logiciel espion, ni vers ou autres logiciels malveillants ;
                n’ait pas un caractère pornographique, sexuel, pédophile ou portant atteinte d’une quelconque manière aux mineurs ou à la protection 
                des enfants et des adolescents. AlloCiné collabore avec les forces de l’ordre et signalera toute exploitation sexuelle d’enfants ;
                ne représente pas des actes répréhensibles, tels que des mauvais traitements infligés à des animaux, la consommation de drogues ou la 
                fabrication de bombes ;
                ne représente pas d’images violentes, ni ne mette en scène des personnes blessées, attaquées ou humiliées ;
                ne représente pas de contenus choquants (images d’accidents, de cadavres…) ;
                ne constitue pas,, sans que ce qui suit soit limitatif, d’apologie ou d'incitation à la réalisation de crimes et délits, d’incitation 
                au suicide, d’incitation à l’usage de drogues ou de substances interdites, de publicité indirecte pour des boissons alcoolisées, 
                le tabac ou les produits du tabac d’incitation à commettre des attentats ; de provocation à la discrimination, à la haine ou à la 
                violence en raison de la race, de l'ethnie, de la religion, du sexe, du handicap, de l’âge, de l’identité sexuelle, du statut de 
                vétéran ou de la nation ;
                ne soit pas contraire à l’ordre public et aux bonnes mœurs.
            
            Les vols, persécutions, menaces, harcèlements, le non-respect de la vie privée ou la divulgation de données personnelles d’autres membres 
            ne sont pas tolérés.
            
            L’Utilisateur ne crée pas de descriptions, tags, titres ou vignettes pouvant prêter à confusion pour attirer un plus grand nombre d’internautes. 
            L’Utilisateur s’engage à ne pas publier de grandes quantités de contenus non ciblés, indésirables ou répétitifs.
            
            Les espaces des forums de discussion et des commentaires ne peuvent en aucun cas être utilisés à des fins professionnelles.
            
            Tout message publicitaire et/ou de parrainage dans le Contenu Utilisateur est interdit.
            
            L’Utilisateur est entièrement et seul responsable de la licéité et de l’utilisation des Contenus Utilisateur qu’il publie ou qu’il transmet 
            par le biais des Services, et garantit AlloCiné contre toutes réclamations et/ou actions de tiers.
            
            AlloCiné se réserve le droit de limiter la capacité de stockage du Contenu Utilisateur que l’Utilisateur met en ligne.
            
            AlloCiné ne peut en aucun cas être tenue responsable en cas d’illicéité ou d’utilisation illicite du Contenu Utilisateur.
            
            Compte tenu du nombre d’informations et de contenus pouvant être mis en ligne, AlloCiné n’a aucune obligation de vérifier d’une manière 
            quelconque lesdites informations et/ou contenus avant leur mise en ligne.
            
            AlloCiné dispose de la faculté, à sa seule discrétion, de supprimer immédiatement tout Contenu Utilisateur qui apparaitrait illicite, 
            et notamment tout Contenu Utilisateur ayant fait l’objet d’une réclamation, fondée ou non, et, notamment, susceptible de porter atteinte 
            aux droits de tiers et/ou contraire aux présentes Conditions Générales, et/ou de supprimer le compte de l’Utilisateur, et/ou de bloquer 
            toute nouvelle demande d’inscription.
            
            L’Utilisateur accepte expressément cette faculté d’AlloCiné, et s’engage à ne former aucune réclamation contre AlloCiné en cas de suppression 
            d’un Contenu Utilisateur pour quelque raison que ce soit.
            
            En soumettant un Contenu Utilisateur quel qu’il soit (notamment, et sans que cette liste soit exclusive, critiques, commentaires, images, 
            vidéos, soumissions d’idées, suggestions et publications de messages sur les forums) sur le Site, l’Utilisateur accorde à AlloCiné, en vue 
            d’exploiter le Contenu Utilisateur en tout ou en partie, en dehors de l’espace dans lequel l’Utilisateur l’a mis en ligne sans intervention 
            d’AlloCiné, un droit et une licence irrévocable, à titre non exclusif, pour le monde entier et à titre gracieux, pour la durée de protection 
            des droits d’auteur telle que prévue dans le code de la propriété intellectuelle, d’utiliser, reproduire, modifier, adapter, publier, exploiter, 
            exécuter, communiquer, représenter, traduire, sous-licencier, créer des œuvres dérivées, et distribuer du Contenu Utilisateur, ou incorporer 
            un Contenu Utilisateur dans quelque forme que ce soit, media, ou toute technologie connue ou inconnue à ce jour, notamment pour faire 
            la promotion d’AlloCiné et de ses services et donne son accord pour toute utilisation à ces fins.
            
            Dans la limite autorisée par la loi, l’Utilisateur reconnaît et accepte, par les présentes, et compte tenu du type de Services objet des 
            présentes Conditions Générales, qu’il a conscience du risque de diffusion du Contenu Utilisateur, et du risque d’adaptation et/ou modification 
            ce Contenu et accepte cette possibilité. L’Utilisateur reconnaît en outre que, pour les mêmes raisons, son nom et sa qualité d’auteur 
            ne pourront être systématiquement associés à son Contenu Utilisateur, et accepte ces conditions d’exploitation.
        </p>
        <p class="cgu">
            
            9. Sanctions en cas de non respect des Conditions Générales
            
            En cas de violation par l’Utilisateur de l’une quelconque des dispositions des Conditions Générales, AlloCiné se réserve le droit de suspendre
            temporairement ou définitivement, sans aucun avertissement préalable et à sa seule discrétion, l’accès et l’utilisation du Compte Utilisateur, 
            du Site et des Services, sans dédommagement.
            
            Par ailleurs, AlloCiné dispose de la faculté de suspendre l’accès au Compte Utilisateur et l’utilisation des Services à tout moment.
            
            Si l’Utilisateur dispose de plusieurs Comptes Utilisateur, toute violation des règles relatives à l’un des Comptes permet à AlloCiné d’appliquer 
            les sanctions prévues par le présent article à l’ensemble des Comptes.
            
            En conséquence d’une suspension définitive, le Compte Utilisateur sera clôturé et toute nouvelle demande d’inscription pourra être bloquée. 
            Les Utilisateurs dont le Compte a été supprimé par AlloCiné, ou qui se sont vus interdire l’accès aux Services mis en ligne par AlloCiné, 
            ne peuvent créer de nouveau Compte, ni utiliser les Services, sauf autorisation d’AlloCiné.
            
            Les sanctions décrites ci-dessus peuvent être infligées sans préjudice de toute poursuite, pénale ou civile, dont l’Utilisateur pourrait faire 
            l’objet de la part des autorités publiques, de tiers, ou d’AlloCiné.
        </p>
        <p class="cgu">
           
            10. Révision des Conditions Générales
            
            AlloCiné se réserve la possibilité de modifier tout ou partie des présentes Conditions Générales. L’Utilisateur sera informé par tous moyens 
            des nouvelles conditions générales afin de les soumettre à son acceptation.
            
            En cas de modification des présentes Conditions Générales, il sera demandé à l’Utilisateur d’accepter les nouvelles Conditions Générales lors 
            de la connexion suivant ladite modification. Les Conditions Générales modifiées ne seront applicables à l’Utilisateur qu’une fois qu’il les 
            aura expressément acceptées.
            
            Toutefois, en cas de changement des informations mentionnées à l’article 2, l’Utilisateur en sera informé mais ces changements ne seront pas 
            considérés comme des changements des présentes Conditions Générales.
        </p>
        <p class="cgu">
            
            11. Acceptation et durée des Conditions Générales
            11.1. Acceptation
            
            Les présentes Conditions Générales prennent effet à la date de leur acceptation par l’Utilisateur dans les conditions définies ci-avant.
            11.2. Durée
            
            Les présentes Conditions Générales sont conclues entre AlloCiné et l’Utilisateur pour une durée non déterminée.
            
            L’Utilisateur est libre d’y mettre fin par l’envoi d’un courriel avec un préavis de quinze (15) jours à l’adresse indiquée à l’article 1.1 
            ci-dessus, ou, plus simplement, en cessant d’utiliser le Site et/ou les Services pendant plus de trois (3) mois.
            
            AlloCiné est libre de mettre fin aux présentes Conditions Générales par l’envoi d’un courriel à l’Utilisateur avec un préavis de quinze (15) 
            jours, ou lorsque l’Utilisateur a cessé d’utiliser le site et/ou les Services pendant plus de trois (3) mois.
            
            Il est toutefois précisé que les stipulations des Conditions Générales mises à disposition de l’Utilisateur antérieurement au jour de la prise 
            d’effet de la résiliation seront maintenues en ce qu’elles régissent les Services utilisés antérieurement au jour de la résiliation.
        </p>
        <p class="cgu">
            
            12. Validité des Conditions Générales
            
            Si une ou plusieurs stipulations des présentes Conditions Générales sont tenues pour non valides ou déclarées telles en application d'une loi, 
            d'un règlement ou à la suite d'une décision définitive d'une juridiction compétente, les autres stipulations garderont toute leur force et leur portée.
            
            Les parties conviennent alors de remplacer la clause déclarée nulle et non valide par une nouvelle stipulation qui se rapprochera le plus, 
            quant à son contenu et quant à l'équilibre de la clause, à celle initialement arrêtée.
        </p>
        <p class="cgu">
            
            13. Loi applicable, conflits et juridiction compétente
            13.1. Loi applicable
            
            Le Site et les présentes Conditions Générales sont soumis à la loi française.
            13.2. Conflits - Juridiction compétente
            
            Avant toute saisine d’un tribunal, l’Utilisateur s’engage à informer AlloCiné de toute difficulté, par courrier postal adressé à AlloCiné, 
            2, rue Paul Vaillant Couturier 92300 Levallois-Perret - France et à rechercher, à la demande de AlloCiné, une solution amiable.
            Charte et modération
        </p>
        <p class="cgu">
            1. L’utilisateur est responsable des commentaires et critiques qu’il adresse au site AlloCiné ; il est tenu au respect des dispositions 
            légales et réglementaires en vigueur, en particulier celles qui répriment les abus de la liberté d’expression.
            
            Il veille à ce que ses commentaires et critiques ne comportent pas, notamment :
            
                de propos à caractère raciste, xénophobe, antisémite, homophobe, négationniste, pornographique, pédophile, pédopornographique, zoophile…
                de propos injurieux, irrespectueux, vulgaires, agressifs, diffamatoires, ou portant atteinte à la vie privée, et plus généralement aux droits 
                de la personnalité de quiconque
                de propos portant atteinte à la dignité humaine, à l’usurpation d’identité
                de propos incitant à la violence, meurtre, viol, au suicide, au terrorisme, à la prostitution, à l’utilisation, la fabrication 
                ou la distribution de substances illicites…
                de propos incitant à la commission de crimes ou de délits ou qui en font l’apologie et plus particulièrement les crimes contre l’humanité
                de contenus violant les droits de respect de la vie privée, de propriété intellectuelle de tiers (notamment articles, ouvrages), 
                pour lesquels il ne dispose pas des autorisations nécessaires des auteurs et/ou ayants droit et en faisant l’apologie du piratage, 
                peer-to-peer, streaming, torrents ou lien/url de téléchargement
                de contenus faisant la promotion de services à but lucratif
            
            Pour les critiques plus particulièrement, l’utilisateur veille à ce que ses critiques ne comportent pas :
            
                de spoilers (ou utilise la balise SPOILERS prévue à cet effet)
                d’erreur de notation sur un film ou une série (cohérence entre le nombre d’étoile et la critique)
                de hors-sujet ou messages non argumentés
                de poster une critique sans avoir vu le film, la série
            
            Le commentaire et/ou critique adressé par l’utilisateur ne pourra pas davantage contenir de lien renvoyant vers de tels contenus.
            
            Tout faux profil sera immédiatement supprimé.
            
            Cette liste est non limitative et l’utilisateur est informé qu’AlloCiné sera libre de supprimer tout commentaire ou critique comportant 
            des propos violant des dispositions légales ou réglementaires, ou contraires à la présente charte. Cette possibilité n'est pas exclusive 
            de la possibilité prévue à l'article précédent de suspendre ou supprimer le compte de l’utilisateur, le cas échéant.
            
            La modération ne permettant pas de déceler a priori tous les contenus illicites et notamment les contenus portant atteinte aux droits des tiers, 
            l’utilisateur garantit AlloCiné contre toute action ou réclamation consécutive à la mise en ligne de son commentaire et de sa critique, 
            si ceux-ci s’avèrent illicites.
            
            Il est également rappelé à l’utilisateur que si son commentaire ou sa critique présente un caractère illicite, les données permettant de 
            l’identifier ou d’identifier son ordinateur pourront être communiquées par les hébergeurs du site AlloCiné à l’autorité judiciaire, 
            si cette dernière le requiert, conformément à l’article 6-II de la loi du 21 juin 2004.
            
            2. Le site AlloCiné, s’il permet de confronter des opinions sur le cinéma et les séries, n’est en aucune façon un site de rencontre. 
            Les utilisateurs peuvent réagir aux commentaires mis en ligne, mais il leur est demandé d’éviter toute invective, interpellation ou sollicitation. 
            Ils ne pourront en aucun cas échanger des coordonnées afin d’entrer en contact avec d’autres utilisateurs du site. Tout échange ou contact 
            direct entre deux utilisateurs sera considéré comme contraire à la présente charte, et sera donc, le cas échéant, de la seule responsabilité 
            de ces derniers. En aucun cas AlloCiné ne pourra être poursuivi ni sa responsabilité recherchée du fait d’un échange ou contact direct entre utilisateurs.
            
            3. L’utilisation du site AlloCiné par les personnes mineures se fait sous la responsabilité et la surveillance de leurs parents et responsables légaux.
            
            4. AlloCiné met à disposition de l’utilisateur un lien « signaler un abus » lui permettant de signaler les abus sur les commentaires et critiques 
            pouvant être considérés comme non conformes aux présentes conditions générales d’utilisation ou à la loi. AlloCiné sera libre des suites données 
            à cette alerte. Il sera par conséquent libre de retirer un commentaire ou une critique qu’il estime non conforme aux présentes conditions 
            générales d’utilisation ou à la loi, et ceci sans formalité ni avertissement préalable.
            
            5. L’équipe de modération d’AlloCiné examine les commentaires et critiques reçus. Il est donc demandé à l’utilisateur de ne pas réitérer 
            inutilement l’envoi d’un commentaire, de ne pas poster le même commentaire ou critique sous différents pseudos, et de bannir toute technique 
            de type spam, "junk mail", "troll"…
            
            AlloCiné est libre de publier ou non les commentaires et les critiques de son choix, ce choix étant entièrement discrétionnaire.
            
            L’utilisateur sera informé en accédant à son compte personnel de l’état de ses commentaires et critiques et notamment ceux validés.
            
            L’utilisateur en adressant son commentaire et sa critique accepte que ceux-ci soient reproduits selon les règles d’indexation et de mise en 
            forme et de mise en valeur qui sont du seul ressort de WEBEDIA, en sa qualité d’éditeur du site allocine.fr et allocine.com.
            
            Pour améliorer la lisibilité des commentaires et des critiques, AlloCiné veille ainsi au respect des erreurs d’expression (orthographe, typographie…) 
            mais ne peut tout rectifier. Les réactions entièrement formulées en lettres capitales (majuscules) ou dont le sens est rendu incertain par des 
            abréviations ou des erreurs de langage (orthographe, vocabulaire, syntaxe, grammaire, message vide ou illisible, langage SMS) ne seront pas retenues.
            
            AlloCiné se réserve la possibilité d’interrompre un débat qui deviendrait redondant ou qui serait investi par un flux de militants pour quelque 
            cause que ce soit en supprimant l’accès à ses services (prosélytisme religieux, secte, attaque d’une religion…).
            
            6. L’utilisateur reconnaît que son commentaire ou sa critique adressé à AlloCiné est une simple réaction sur un sujet d’information, postée 
            sur un site média, et qu’à ce titre il est public, libre de droits, et peut être librement diffusé, réutilisé, commenté. A toute fin utile 
            et dans l’hypothèse où un commentaire ou une critique serait susceptible de supporter des droits de propriété intellectuelle et notamment 
            un droit d’auteur, l’utilisateur, en postant ce commentaire ou cette critique, accepte de céder gracieusement à AlloCiné l’ensemble de ses 
            droits, comportant le droit de reproduction, de représentation, d’adaptation, de traduction, de diffusion et ce pour toute la durée de 
            la protection légale. Cette autorisation est donnée pour la publication du commentaire et de la critique sur le site allocine.fr et 
            allocine.com tel que défini à l’article 1 ci-dessus, quelle que soit la forme de cette publication et les procédés de mise en valeur 
            du commentaire et de la critique. Toujours dans le cadre de cette autorisation gracieuse, AlloCiné pourra sélectionner le commentaire 
            et la critique et les publier en tout ou partie sur internet ou dans toute autre publication éditée par ses filiales ou toute société 
            du même groupe. La présente cession de droits vaut pour tout support et tout mode de consultation (y compris tous supports numériques, 
            presse, applications mobiles…), et sans limitation de territoire.
            Règles de bonne conduite
            Respectez la communauté AlloCiné
            
            Nous vous demandons simplement de ne pas utiliser le site de manière abusive. Sur AlloCiné, toute nouvelle fonction s'appliquant aux 
            communautés implique un certain niveau de confiance. Une confiance que nous vous accordons. Alors, tout comme des millions d'autres 
            utilisateurs, respectez cette confiance et agissez de manière responsable.
            Nous procédons à une vérification des vidéos signalées comme pouvant offenser
            
            De notre côté... Lorsqu'une vidéo est signalée comme pouvant offenser, nous la vérifions pour déterminer si elle est contraire aux 
            conditions d'utilisation. Les vidéos signalées ne sont pas automatiquement supprimées par le système. Si nous supprimons votre vidéo 
            après l'avoir vérifiée, nous avons une bonne raison de le faire et notre avertissement est à prendre au sérieux. Respirez profondément, 
            lisez nos conditions d’utilisation et essayez de comprendre notre point de vue. Si vous trouvez d'autres vidéos sur AlloCiné qui dérogent 
            à nos conditions, veuillez les signaler pour que nous puissions également les vérifier !
            Restons corrects
            
            Voici quelques principes de base qui vous permettront d'éviter les problèmes :
            
                AlloCiné n'est pas destiné à la pornographie ni au contenu à caractère sexuel. Si cela décrit le type de contenu de votre vidéo, 
                même s'il s'agit d'une vidéo de vous-même, ne la publiez pas sur AlloCiné. Sachez, en outre, que nous collaborons étroitement avec 
                les forces de l'ordre et que nous signalons toute exploitation sexuelle d'enfants.
                Ne publiez pas de vidéos représentant des actes répréhensibles, tels que les mauvais traitements infligés à des animaux, la consommation 
                de drogues ou la fabrication de bombes.
                Les images violentes ou la violence gratuite sont interdites. Si votre vidéo met en scène des personnes blessées, attaquées ou humiliées, 
                ne la publiez pas.
                AlloCiné n'est pas un site destiné à choquer. Ne publiez pas de vidéos choquantes d'accidents, de cadavres ou autres choses de ce genre.
                Respectez les droits d'auteur. Mettez en ligne uniquement vos vidéos ou celles que vous êtes autorisé à utiliser. En d'autres termes, 
                ne mettez pas en ligne une vidéo si vous n'en êtes pas l'auteur et n'incluez pas dans votre vidéo du contenu pour lequel vous ne disposez 
                pas des droits si vous n'avez pas obtenu les autorisations requises. Ces éléments peuvent être des pistes audio, des extraits de 
                programmes protégés par des droits d'auteur ou des vidéos créées par un tiers.
                Nous encourageons la liberté d'expression et défendons le droit de chacun à exprimer des points de vue peu populaires. Mais nous 
                n'autorisons pas les discours incitant à la haine, qui attaquent ou rabaissent un groupe en raison de la race, l'origine ethnique, 
                la religion, le handicap, le sexe, l'âge, le statut de vétéran ou l'identité sexuelle.
                Les vols, persécutions, menaces, harcèlements, le non-respect de la vie privée ou la divulgation de données personnelles d'autres 
                membres ne seront pas tolérés. Toute personne surprise en train de commettre ces actes se verra définitivement exclue d’AlloCiné.
                Tout le monde déteste recevoir du spam. Ne créez pas de descriptions, tags, titres ou vignettes pouvant prêter à confusion pour 
                attirer un plus grand nombre d'internautes. Vous n'avez pas le droit de publier de grandes quantités de contenus non ciblés, indésirables ou répétitifs.
            
            Violation des Droit d'Auteurs
            
            Pour signaler tout abus, harcèlement, contenu pouvant offenser ou réclamation relative à la confidentialité, envoyez un email 
            à reclamations@allocine.fr. Pour envoyer une notification d'infraction, vous devez d'abord nous faire parvenir un communiqué écrit 
            contenant les informations indiquées, en respectant le format suivant :
            
                Envoyez-nous une déclaration stipulant que vous avez trouvé une vidéo sur AlloCiné qui, selon vous, constitue une infraction à 
                vos droits d'auteur. Exemple : "Je confirme par la présente que j'estime que la vidéo identifiée ci-dessous constitue une infraction 
                à mes droits d'auteur".
                Indiquez-nous le pays dans lequel vos droits d'auteur s'appliquent.
                Indiquez-nous le titre de la vidéo et l'URL complète de sa page de lecture.
                Expliquez-nous pourquoi la vidéo porte atteinte à vos droits d'auteur (le son a été copié, l'ensemble de la vidéo est une copie
                d'une de vos œuvres originales, etc.).
                Identifiez la nature (film, morceau de musique, livre, etc.) et les informations (titre, éditeur, dates, etc.) de la vidéo dont 
                vous êtes le titulaire des droits et qui vous semblent faire l'objet d'une infraction. Si ces informations sont disponibles sur 
                Internet, nous vous conseillons de nous envoyer le lien.
                N'oubliez pas de nous fournir vos coordonnées pour que nous puissions vous répondre (adresse électronique de préférence).
                Donnez-nous vos coordonnées que nous pourrons faire suivre à l'expéditeur de la vidéo concernée. Ainsi, il pourra prendre contact 
                directement avec vous pour résoudre le litige (adresse e-mail de préférence).
                Ajoutez la déclaration suivante : "Je pense en toute bonne foi que l'utilisation du travail protégé par droits d'auteur décrite 
                ci-dessus n'est pas autorisée par le titulaire des droits d'auteur (ou par un tiers le représentant) et n'est pas non plus autorisée par la loi."
                J'atteste que les informations contenues dans cette notification sont exactes et que je suis le titulaire des droits d'auteur, ou que 
                je dispose d'un droit exclusif me permettant de signaler une infraction conformément à ce droit.
                Signez la déclaration. Si vous envoyez la déclaration par e-mail, vous pouvez y joindre votre signature scannée ou électronique.
            
            Pour nous permettre de traiter votre demande dans les délais les plus brefs, nous vous remercions d'adresser de telles notifications écrites 
            à la personne qualifiée à l'aide du formulaire de réclamation relative aux droits d'auteur ci-après. Vous devez posséder un compte CinemALL
            pour utiliser cet outil.
            
            Vous devez être sûr que le contenu que vous avez vu sur AlloCiné constitue une infraction à vos droits d'auteur. Si vous n'êtes pas sûr 
            de bien connaître vos droits ou si vous n'êtes pas sûr qu'il y a atteinte à vos droits d'auteur, adressez-vous à un conseiller juridique 
            avant de poursuivre. Attention : Dans votre pays, vous risquez peut-être des poursuites en cas d'allégation de mauvaise foi concernant des 
            infractions aux droits d'auteur dans le cadre de ce processus. Ne faites pas de fausses réclamations !
            Notez également que les informations de cette notification légale peuvent être transmises à la personne ayant fourni le contenu présumé en infraction.
            
            Les informations de la personne ayant déposé la réclamation seront publiées sur AlloCiné à la place du contenu supprimé.
            Conditions générales d’utilisation de la billetterie en ligne
            
            AlloCiné met à disposition de l’Utilisateurs un service de réservation de place de cinéma en ligne. Par le biais de ce service, CinemALL
            propose de mettre en relation l’utilisateur et les exploitants de salles de cinéma partenaires en vue de l’achat de place de cinéma ou de 
            contenu alternatif (notamment opéra, ballet…). A ce titre, AlloCiné n’intervient qu’en tant qu’intermédiaire et ne saurait être considéré 
            comme ayant qualité de vendeur. Les obligations liées à la qualité de vendeur pèsent sur la personne de l’exploitant de salle partenaire, 
            qui fixe le prix de vente de ses billets et en assure le service après-vente. Les exploitants de salles partenaires sont en outre susceptibles 
            de facturer à l’utilisateur des frais de gestion lors de la commande.
            
            L’utilisateur peut accéder au service de billetterie en ligne sur les pages AlloCiné dédiées à chaque film en cliquant sur le lien 
            redirigeant vers l’url ticket.allocine.fr. L’achat est limité à 9 billets de chaque type (plein tarif, tarif réduit et tarif étudiant) par transaction.
            
            Les conditions générales de vente applicables à de telles transactions sont celles des exploitants de salles partenaires. Ces conditions 
            vous seront communiquées avant tout achat sur la billetterie en ligne AlloCiné et sont fixées par chaque exploitant. AlloCiné ne saurait 
            être tenue responsable en cas de non-conformité de ces conditions générales de vente avec la législation en vigueur.
            
            La liste de l’ensemble des exploitants de salles partenaires d’AlloCiné est disponible à l’adresse suivante : https://www.allocine.fr/service/ticketing/ .
            
            Au cours de l’utilisation du service de billetterie en ligne, l’Utilisateur pourra être sollicité afin de fournir les informations suivantes 
            à AlloCiné : nom, prénom, adresse e-mail et informations bancaires. L’Utilisateur accepte que ces informations soient utilisées par les 
            exploitants de salles partenaires avec lesquels il effectue une transaction. Une fois la confirmation de sa commande effectuée sur la page 
            dédiée, l’utilisateur se verra envoyé un e-mail contenant en pièce jointe le billet à imprimer. Il pourra également imprimer son billet 
            sur la page de confirmation de la commande. Selon les termes des conditions de vente de chaque exploitant de salle partenaire, 
            l’utilisateur aura éventuellement la possibilité d’annuler la transaction ou d’exercer un droit de rétractation. AlloCiné ne saurait 
            être tenu responsable en cas de refus de la part de l’exploitant de salle de laisser l’utilisateur exercer cette possibilité ou ce droit.
            
            En cas de litige entre l’utilisateur et un ou plusieurs exploitants de salles de cinéma partenaires, AlloCiné ne saurait être tenu 
            responsable à l’égard des réclamations, demandes, coût ou dépenses et dommages relevant d’une quelconque façon dudit litige..
        </p>
        <p class="cgu">
           
            1. Contacts
            
            Pour toute information ou question, nous sommes à votre disposition :
            Par formulaire de contact : https://www.allocine.fr/service/contact/
            Par courrier : AlloCiné Salles - 2, rue Paul Vaillant Couturier 92300 Levallois-Perret
            2. Propriété intellectuelle
            
            WEBEDIA éditeur du site www.allocine.fr, est titulaire exclusif des droits notamment d’auteur et de tout autre droit de propriété 
            intellectuelle ou industriel se rapportant au site, à son contenu (tels que photographie, texte), sa présentation et l’assemblage 
            des différents éléments qui le compose, en vertu des textes en vigueur. De même WEBEDIA est titulaire exclusif des droits portant 
            sur ses logos, marques et autres signes distinctifs accessibles à partir du site. Toute utilisation du site et de son contenu à des 
            fins autres que privée est interdite. En conséquence, il est interdit de modifier, représenter ou reproduire totalement ou partiellement 
            le site et son contenu et ce quel qu’en soit le support et le procédé utilisé.
            3. Droit applicable
            
            Les présentes conditions générales d'utilisation sont soumises au droit français.
            
            Date de dernière mise à jour : le 28 Juillet 2015
            Conditions générales du service AlloCiné Premium sur les applications mobiles
            
            AlloCiné met à disposition des utilisateurs de ses applications mobiles un service payant permettant d’accéder à des fonctionnalités 
            supplémentaires et de naviguer sans publicité. Avec ce service, AlloCiné propose à certains de ses utilisateurs d’accéder à la version 
            Premium de ses applications par l’intermédiaire de leurs comptes iTunes et Google Play.
            
            Les utilisateurs peuvent accéder au service AlloCiné Premium avec les trois offres suivantes :
            
                Abonnement mensuel pour 0,99€ par mois, renouvelable automatiquement.
                Abonnement trimestriel pour 2,99€ tous les trois mois, renouvelable automatiquement.
                Abonnement annuel pour 9,99€, permettant l'accès pour un an, non renouvelable.
            
            Pour les utilisateurs de l’application AlloCiné sur iPhone, iPad ou iPod le paiement sera effectué depuis leurs comptes iTunes à la 
            confirmation de l'achat. L'abonnement est renouvelable automatiquement à moins qu'il ne soit désactivé au moins 24h avant la fin 
            de la période courante. Aucun désabonnement de la période courante n'est autorisé pendant la durée active de l'abonnement.
            
            L’abonnement et son renouvellement peuvent être gérés en se rendant directement sur les pages dédiées aux comptes des utilisateurs 
            dans l’App Store, après l’achat.
            Contacts
            
            Pour toute information ou question relative à AlloCiné Premium, nous sommes à votre disposition :
            Par e-mail : mobile@allocine.com
            Par courrier : AlloCiné Equipe Mobile - 2, rue Paul Vaillant Couturier 92300 Levallois-Perret

	</main>
	<footer>
		<?php require_once "includes/partials/footer.phtml"; ?>
	</footer>
<script src="public/scripts/script.js"></script>
</body>
</html>