<?php
	ini_set('display_errors', 'on');
	require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta name="description" content="Cookies de CinemALL">
	<?php require "includes/partials/page_head.phtml"; ?>
	<link href='https://fonts.googleapis.com/css?family=Russo+One' rel='stylesheet'>
	<link rel="stylesheet" href="public/styles/styles.css" type="text/css">
</head>
<body>
	<nav>
		<?php require_once "includes/partials/navbar.phtml"; ?>
	</nav>
	<header>
		<h1 class="cguH1">Politique de cookies</h1>
	</header>
	<main class="content">
		<p class="cgu">
            Le modèle économique du site (ci-après le « Site ») repose historiquement sur l’affichage de publicités personnalisées basées sur l’utilisation 
            de cookies publicitaires, qui permettent de suivre la navigation des internautes et cibler leurs centres d’intérêts. La nouvelle réglementation 
            relative aux cookies ne permet plus au Site de s’appuyer sur cette seule source de revenus. En conséquence, afin de pouvoir maintenir le 
            financement du Site et fournir les services proposés tout en vous offrant une même qualité de contenu éditorial sans cesse renouvelé, nous 
            vous offrons la possibilité d’exprimer votre choix entre les deux alternatives suivantes d’accès :
            
                Accéder au site pour 2€ pendant 1 mois sans cookie publicitaire
                Accéder au site gratuitement en acceptant les cookies publicitaires
            
            Cette page a ainsi pour but de vous informer de manière claire et transparente de l’utilisation des cookies et autres traceurs lorsque 
            vous consultez le Site.
        </p>
        <p class="cgu">
            
            1. Qu'est ce qu'un cookie ?
            
            Lors de la consultation d’un service en ligne, des informations sont enregistrées dans des témoins de connexion, qui sont des fichiers texte, 
            communément appelés « cookies », installés dans un espace dédié du disque dur de votre terminal (ordinateur, smartphone ou tablette). 
            Les cookies vont être utilisés pour envoyer des informations au navigateur de l’internaute et permettre à ce navigateur de renvoyer des 
            informations au site d’origine (par exemple un identifiant de session ou le choix d’une langue).
            
            Seul l'émetteur du Cookie concerné est susceptible de lire ou de modifier les informations qui y sont contenues.
        </p>
        <p class="cgu">
    
            Lors de votre visite sur le Site, nous vous informons que des cookies sont installés sur votre équipement terminal.
            2. Autres types de traceurs
            
            D’autres types de traceurs sont également utilisés, tels que les pixels invisibles, également appelés web bugs ou balises web. Ceux-ci 
            se présentent sous forme d’images graphiques minuscules et peuvent être placés sur le Site ou dans un courriel.
            
            Leur fonction est de collecter des informations techniques (par exemple votre adresse IP ou le type d’appareil que vous utilisez) et 
            des informations sur votre activité (par exemple la date et l’heure de la consultation d'une page) ou de permettre le dépôt d’un cookie 
            pour renvoyer ces informations à un serveur.
            
            Les pixels invisibles placés sur les courriels ont pour finalité de suivre certains de vos comportements, tels que l’ouverture du courriel 
            ou le clic sur un lien présent au sein du courriel, afin de :
            
                mesurer l'impact des campagnes de prospection ;
                mesurer votre niveau d’implication vis-à-vis de leurs contenus et vous fournir un contenu plus pertinent.
        
        </p>
        <p class="cgu">
            
            3. Quels sont les cookies déposés et autres traceurs utilisés pendant votre navigation sur le site ?
            
            Les cookies et autres traceurs utilisés (ci-après dénommés ensemble les « Cookies ») sont utilisés sur le Site pour différentes finalités, 
            à savoir pour faciliter votre navigation, vous proposer des contenus et publicités ciblés et pour réaliser des statistiques de visites.
            Les Cookies techniques
            
            Lors de votre navigation sur le Site, deux types de Cookies techniques sont déposés sur votre terminal :
            
                Les Cookies qui ont pour finalité exclusive de permettre ou faciliter la communication par voie électronique :
                    Détecter des erreurs de connexion
                    Assurer la sécurité du Site
                    Permettre l’authentification
                    Optimiser la charge / la vitesse d’affichage
                Les Cookies strictement nécessaires à la fourniture d'un service de communication en ligne à la demande expresse de l'utilisateur 
                (ces Cookies permettent de produire le service tel qu'attendu par les internautes) :
                    Conserver les consentements Cookies : selon que vous choisissiez de souscrire à l’offre payante pour accéder au Site sans le dépôt 
                    de cookie publicitaire ou que vous choisissiez d’accéder au Site avec le dépôt de cookies publicitaires, un cookie technique stockant votre 
                    choix sera déposé sur votre terminal.
                    Localiser votre terminal : si vous souhaitez rechercher un lieu proche de votre localisation.
                    Mémoriser les informations relatives, par exemple, à un formulaire que vous avez rempli ou à un service (inscription, accès à votre compte)
                    Personnaliser l’interface : le choix de la langue par exemple.
            
            Ces Cookies techniques reposent sur notre intérêt légitime et sont déposés dès votre arrivée sur le Site pour vous délivrer un service de qualité.
            Les Cookies de mesures d’audience
            
            Quelle que soit l’option choisie : accéder au Site en souscrivant à l’offre payante ou en y accéder gratuitement, des Cookies de mesures d’audience 
            sont déposés.
            
            Ces Cookies ont pour finalité de nous permettre de mieux comprendre l’utilisation que vous faites de nos services, de détecter d’éventuels 
            dysfonctionnements et ainsi améliorer nos outils.
            
            Les données générées par ces Cookies concernent notamment :
            
                votre utilisation du site, tel que les pages que vous avez visitées ;
                votre adresse IP afin de déterminer la ville de connexion. Cette donnée est immédiatement anonymisée après localisation et n’est pas communiquée 
                à Google.
            
            Les Cookies permettant ces finalités reposent sur notre intérêt légitime et sont déposés dès votre arrivée sur le Site pour vous délivrer un service 
            de qualité. Vous pouvez néanmoins vous opposer à ces Cookies en cliquant ici.
            
            Si vous choisissez d’accéder au Site gratuitement, nous vous informons que les Cookies Google Analytics seront également déposés à des fins publicitaires. 
            Par conséquent, ils reposeront sur votre consentement.
            Les Cookies publicitaires
            
            Les Cookies publicitaires ont pour finalité de nous permettre d’adapter les publicités diffusées sur notre Site ou sur ceux de nos partenaires en 
            fonction de vos centres d’intérêt, mesurer votre interaction avec ces publicités (impression, clics, comportement généré par le clic), mesurer 
            l’efficacité de la campagne publicitaire pour rémunérer nos partenaires publicitaires et limiter la fréquence d’affichage.
            
            Ces Cookies publicitaires sont déposés par l’intermédiaire de code informatique, dit “tag“, fournis par nos partenaires commerciaux et que nous 
            intégrons dans le code source des pages de notre site. Ils peuvent également être insérés par nos partenaires via les publicités affichées sur le site.
            
            En choisissant d’accéder au Site gratuitement, vous consentez à ce que ces Cookies soient déposés lors de votre navigation sur le Site. Si, en revanche, 
            vous choisissez de souscrire à l’offre payante, aucun cookie publicitaire ne sera déposé sur votre terminal.
            
            L’émission et l’utilisation de ces cookies publicitaires et autres traceurs par des partenaires sont soumises à leur propre politique de protection 
            de la vie privée. Pour plus d’informations concernant ces traitements et les durées de conservation des Cookies fixées par ces partenaires publicitaires, 
            rendez-vous directement sur notre plateforme de gestion des consentements accessible ici.
            Les autres traceurs
            
            Lors de votre navigation sur nos sites web ou lorsque vous utilisez nos applications mobiles, nous pouvons être amenés à partager avec notre partenaire 
            LiveRamp et les sociétés de son groupe des données personnelles que nous recueillons auprès de vous, telles que votre adresse e-mail (sous forme 
            hachée et pseudonyme), votre adresse IP, votre identifiant publicitaire mobile ou des informations sur votre navigateur ou votre système d'exploitation. 
            LiveRamp utilise ces informations pour créer un code d'identification en ligne afin de vous reconnaître sur vos appareils sans permettre de vous 
            identifier directement. Nous pouvons placer ce code dans notre cookie ou dans un cookie LiveRamp et autorisons son partage avec nos partenaires 
            publicitaires ainsi qu'avec d'autres sociétés tierces dans le monde entier afin de leur permettre de personnaliser le contenu et les publicités 
            qui vous sont proposées en fonction de vos intérêts, tout au long de votre expérience en ligne (web, emails, apps mobiles, objets connectés, etc). 
            Ces sociétés peuvent à leur tour utiliser ce code pour y associer les informations démographiques ou d'intérêt que vous avez fournies lors de 
            vos interactions avec eux. Vous pouvez vous opposer au traitement de vos données personnelles à tout moment en cliquant sur ce lien.
        </p>
        <p class="cgu">
            
            4. Quels sont vos choix concernant les cookies ?
            
            Vous disposez de différents moyens pour faire vos choix en matière d’acceptation ou de refus des Cookies déposés sur votre terminal.
            1. Gérer vos choix via notre plateforme de gestion des consentements
            
            Nous mettons à votre disposition un outil simple qui vous permet de faire vos choix et le cas échéant de vous opposer au dépôt de Cookies sur notre site. 
            Les choix que vous ferez grâce à cet outil ne seront valables que dans le cadre de votre navigation sur le site.
            2. Gérer vos choix via votre configuration de logiciel de navigation
            
            Vous pouvez configurer votre logiciel de navigation de manière à ce que des Cookies soient enregistrés dans votre équipement terminal 
            ou qu'ils soient rejetés, soit systématiquement, soit selon leur émetteur.
            
            Vous pouvez également choisir de supprimer tous les Cookies anciennement déposés, notamment si vous choisissez de modifier vos choix.
            
            A titre de précision, la configuration de chaque navigateur est différente. Pour vous aider dans cette configuration, vous pouvez consulter 
            la page d’aide spécifique au navigateur que vous utilisez.
            
            A titre d’exemples :
            
                Microsoft Internet Explorer : ici
                Microsoft Edge: ici
                Google Chrome: ici
                Safari Mac: ici
                Safari iPhone/Ipad: ici
                Firefox: ici
                Opera: ici
            
            Nous vous informons que :
            
                Si vous refusez ou choisissez de retirer votre consentement au dépôt de Cookies publicitaires, vous pourrez avoir accès au Site en souscrivant à 
                l’offre payante
                Si vous souscrivez à l’offre payante, des publicités seront toujours visibles lorsque vous accéderez au Site. Cependant, celles-ci ne seront 
                pas basées sur des Cookies publicitaires
                La prise en compte de votre consentement, de votre refus ou du retrait de consentement repose sur un cookie. Par conséquent, si vous supprimez 
                tous les Cookies de votre terminal ou si vous changez de terminal, nous ne serons plus en mesure de connaître l’option choisie
        </p>
        <p class="cgu">
            5. Quelles conséquences peut-il y avoir si vous partagez l'utilisation de votre terminal avec d'autres personnes ?
            
            Si votre terminal est utilisé par plusieurs personnes et lorsqu'un même terminal dispose de plusieurs logiciels de navigation, nous ne pouvons 
            pas nous assurer de manière certaine que les services et publicités destinés à votre équipement terminal correspondent bien à votre propre 
            utilisation de cet équipement terminal et non à celle d'un autre utilisateur de cet équipement terminal.
            
            Le partage avec d'autres personnes de l'utilisation de votre équipement terminal et la configuration des paramètres de votre navigateur à l'égard 
            des cookies et autres traceurs, relèvent de votre libre choix et de votre responsabilité.

        </p>
	</main>
	<footer>
		<?php require_once "includes/partials/footer.phtml"; ?>
	</footer>
<script src="public/scripts/script.js"></script>
</body>
</html>