<?php
	ini_set('display_errors', 'on');
	require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta name="description" content="Page utilisateur CinemALL">
	<?php require "includes/partials/page_head.phtml"; ?>
	<link href='https://fonts.googleapis.com/css?family=Russo+One' rel='stylesheet'>
	<link rel="stylesheet" href="public/styles/styles.css" type="text/css">
</head>
<body>
	<nav>
		<?php require_once "includes/partials/navbar.phtml"; ?>
	</nav>
	<header>
		<?php if (isset($_SESSION['login']) && ($_SESSION['isAdmin'] == 1)) : ?>
			<h1>Mode ADMIN</h1>
		<?php else :?>
			<h1>Page Utilisateur</h1>
		<?php endif; ?>
	</header>
	<main class="">
		<div class="userContainer">
            <img src="<?= $maPersonne->getAvatar() ?>" class="avatar" alt="avatar du profil">
    	</div>
	    <a href="index.php?page=contact&action=edit&id=<?= $maPersonne->getId(); ?>" class="editUser">Modifier mon profil</a>
		    
		    <?php  if (isset($_SESSION['login']) && $_SESSION['login'] != '' && $_SESSION['isAdmin'] == 1) { ?>
		        <script>let idPersonne=<?= $_SESSION['idUser']; ?></script>
		    <? endif ?>
				<div class="addVisu">
					<a href="index.php?page=contact&action=add">Ajouter un contact</a>
				</div>
				<h2>Liste Utilisateur</h2>
				<table class="tableVisu">
					<thead>
						<th>Email</th>
						<!--<th>Password</th>-->
						<th>Avatar</th>
						<th>Date Naissance</th>
						<th colspan="2">Actions</th>
					</thead>
					<tbody class="tableContent">
						<?php
						    foreach ($lesContacts as $unContact) : ?>
						        <tr>
							        <td class="tbVisu"><?= htmlspecialchars($unContact->getEmail()) ?></td>
							        <td class="tbVisu"><?= htmlspecialchars($unContact->getAvatar()) ?></td>
							        <td class="tbVisu"><?= htmlspecialchars($unContact->getDateNaissance()->format('d/m/Y')) ?></td>
							        <td class="tbVisu"><a href="index.php?page=contact&action=edit&id=<?= htmlspecialchars
							        ($unContact->getId()) ?>">Modifier</a></td>
							        <td class="tbVisu"><a href="index.php?page=contact&action=delete&id=<?= htmlspecialchars
							        ($unContact->getId()) ?>">Supprimer</a></td>
						        </tr>
						    <?php endforeach?>
					</tbody>
				</table>
				<h2>Newsletter</h2>
				<table class="tableNewsletter">
					<thead>
						<th>Email</th>
						<!--<th>Password</th>-->
						<th>Date ajout</th>
						<th colspan="2">Actions</th>
					</thead>
					<tbody class="newsletterContent">
						<?php
						    foreach ($lesNewsletters as $uneNewsletter) : ?>
						        <tr>
						        <td class="tbVisu"><?= htmlspecialchars($uneNewsletter->getEmail()) ?></td>
						        <td class="tbVisu"><?= htmlspecialchars($uneNewsletter->getDateEnvoi()) ?></td>
						        <!--<td class='tbVisu'><a href=\"index.php?page=contact&action=edit&id={$unContact->getId()}\">Modifier</a></td> -->
						        <td class="tbVisu"><a href="index.php?page=newsletter&action=delete&id=<?= htmlspecialchars($uneNewsletter->
						        getId()) ?>">Supprimer</a></td>
						        </tr>
						    <?php endforeach ?>
					</tbody>
				</table>
				<?php
			}else{
				echo '<script>if(typeof idPersonne === \'undefined\') {let idPersonne = 0;}</script>';
				?>
				<div class="userListMovie">
				<div class="userMovieFavorite">
					<h2>Vos Films favoris</h2>
						<div class="userFavorite">
					</div>
				</div>
				<div class="userMovieSee">
					<h2>Vos films déjà vu</h2>
					<div class="userSee">
						
					</div>
				</div>
				<div class="userMovieFutur">
					<h2>Films à voir</h2>
					<div class="userFutur">
					
					</div>
				</div>
			</div>
			<?php
			}
			?>
	</main>
	<footer>
		<?php require_once "includes/partials/footer.phtml"; ?>
	</footer>
<script src="public/scripts/script.js"></script>
<script src="public/scripts/script_user_view.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
	    const idFilms = <?= htmlspecialchars(json_encode($idFilms)); ?>;
	    const idFilms2 = <?= htmlspecialchars(json_encode($idFilms2)); ?>;
	    const idFilms3 = <?= htmlspecialchars(json_encode($idFilms3)); ?>;
	    idFilms.forEach(async function(idFilm) {
	      let userInfoPage = await getUserInfo(idFilm);
	      createUserContent(userInfoPage, '.userFavorite');
	    });
	    idFilms2.forEach(async function(idFilm2) {
	      let userInfoPage2 = await getUserInfo(idFilm2);
	      createUserContent(userInfoPage2, '.userSee');
	    });
	    idFilms3.forEach(async function(idFilm3) {
	      let userInfoPage3 = await getUserInfo(idFilm3);
	      createUserContent(userInfoPage3, '.userFutur');
	    });
	});	  
</script> 
</body>
</html>